version: '3.3'

services:
  geth-node:
    build:
      context: geth-node/
    ports:
      - "8545:8545"
      - "30313:30303"
      - "30313:30303/udp"
    networks:
      - bprdqs
    
networks:
  bprdqs:
    driver: bridge
