version: '3.3'

services:
  geth-node:
    build:
      context: geth-node/
    volumes:
      - root/.ethereum:/root/.ethereum
      - /etc/localtime:/etc/localtime:ro
    tty: true
    ports:
      - "8545:8545"
    networks:
      - bprdqs
    
volumes:  
  root:

networks:
  bprdqs:
    driver: bridge
