version: '3.3'

services:
  geth-node:
    build:
      context: geth-node/
    volumes:
      - data:/root
      - /etc/localtime:/etc/localtime:ro
    tty: true
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    networks:
      - bprdqs
    
volumes:  
  data:

networks:
  bprdqs:
    driver: bridge
